languageCode: en-us
theme: blist
title: Evelyn Karah's Playtoy
metaDataFormat: yaml
DefaultContentLanguage: en
DefaultContentLanguageInSubdir: true
languages:
  en:
    contentDir: content/en
    languageName: English
    weight: 1
    params:
      introPhoto: /picture.jpg
      introTitle: Evelyn Karah
      introSubtitle: Trans milf, part-time Princess 
      introSubtitle2: ğŸ‘ ğŸ’–ğŸ’—ğŸ’œâ¤ï¸â€ğŸ”¥ğŸ’™ğŸ’“ğŸ‘ 
      logo: /blist-logo.png
    menu:
      main:
        - name: Blog
          url: blog
          weight: 1
        - name: About
          url: page/about/
          weight: 2
        - name: Tags
          url: tags
          weight: 3
        - name: Top Post
          url: /en/blog/emoji-support/
          weight: 4
  it:
    contentDir: content/it
    description: Modernes Blog-Theme fÃ¼r Ihre Hugo-Site.
    languageName: Italiano
    title: Evelyn Karah's Playtoy
    weight: 2
    params:
      introPhoto: /picture.jpg
      introSubtitle: Milf trans milf, Principessa part-time 
      introSubtitle2: ğŸ‘ ğŸ’–ğŸ’—ğŸ’œâ¤ï¸â€ğŸ”¥ğŸ’™ğŸ’“ğŸ‘ 
      introTitle: Evelyn Karah
      logo: /blist-logo-de.png
    menu:
      main:
        - name: Blog
          url: blog
          weight: 1
        - name: Ãœber mich
          url: page/about/
          weight: 2
        - name: Tags
          url: tags
          weight: 3
params:
  darkModeToggle: true
  enableSearch: true
  copyright: Copyright Â© 2022 - Evelyn Karah Â· All rights reserved
  favicon: /favicon.svg
  ascentColor: bg-blue-100
  frontBundle: blog
  hideMeta: false
  hideOtherLanguages: false
  homepage:
    social:
      description: I work on everything coding and tweet developer memes
      dribbble: 'https://dribbble.com/'
      github: 'https://github.com/'
      linkedin: 'https://linkedin.com/in/'
      medium: 'https://medium.com/'
      reddit: 'https://reddit.com/'
      stackoverflow: 'https://stackoverflow.com/'
      title: Follow me
      twitter: 'https://twitter.com/'
      xing: 'https://www.xing.com/profile/'
menu:
  main:
    - name: About
      url: /about
build:
  writeStats: true
outputs:
  home:
    - HTML
    - RSS
    - JSON
markup:
  highlight:
    style: dracula
  goldmark:
    renderer:
      unsafe: true
